---
name: network-org1
version: 1.0.0
client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
    - peer0.org1.coinkaraoke.com
    certificateAuthorities:
    - ca.org1.coinkaraoke.com
peers:
  peer0.org1.coinkaraoke.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      pem: |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUa/0cbk6E7PVr5JCGrIy0zcKO4iMwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIyMTEyNjAzMjIwMFoXDTM3MTEyMjAzMjIwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl8wUsCjP2E3UP5JiLO1W8P+K
          HNx92jj5tNTDyZShG/SdmSGCYSMpB8tuyoLoyMQdCkFcG9M5Rqetk4I/LsO9j6NF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FHvtqEHP6VTeEEcczWh5HZ7tfdP9MAoGCCqGSM49BAMCA0cAMEQCIDGrsfP5KJUg
          D6qB2YMA/5SKNBNe8693yTpaHicSyvqfAiADPpvubKIidHoFMaEBAHLZ6sTdCkL/
          NVUgwlvJMQPyVw==
          -----END CERTIFICATE-----
          
    grpcOptions:
      ssl-target-name-override: peer0.org1.coinkaraoke.com
      hostnameOverride: peer0.org1.coinkaraoke.com
certificateAuthorities:
  ca.org1.coinkaraoke.com:
    url: https://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: 
        - |
          -----BEGIN CERTIFICATE-----
          MIICFjCCAb2gAwIBAgIUa/0cbk6E7PVr5JCGrIy0zcKO4iMwCgYIKoZIzj0EAwIw
          aDELMAkGA1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQK
          EwtIeXBlcmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMt
          Y2Etc2VydmVyMB4XDTIyMTEyNjAzMjIwMFoXDTM3MTEyMjAzMjIwMFowaDELMAkG
          A1UEBhMCVVMxFzAVBgNVBAgTDk5vcnRoIENhcm9saW5hMRQwEgYDVQQKEwtIeXBl
          cmxlZGdlcjEPMA0GA1UECxMGRmFicmljMRkwFwYDVQQDExBmYWJyaWMtY2Etc2Vy
          dmVyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEl8wUsCjP2E3UP5JiLO1W8P+K
          HNx92jj5tNTDyZShG/SdmSGCYSMpB8tuyoLoyMQdCkFcG9M5Rqetk4I/LsO9j6NF
          MEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYDVR0OBBYE
          FHvtqEHP6VTeEEcczWh5HZ7tfdP9MAoGCCqGSM49BAMCA0cAMEQCIDGrsfP5KJUg
          D6qB2YMA/5SKNBNe8693yTpaHicSyvqfAiADPpvubKIidHoFMaEBAHLZ6sTdCkL/
          NVUgwlvJMQPyVw==
          -----END CERTIFICATE-----
          
    httpOptions:
      verify: false
